unamfi/sistop-2024-2

practicas/1/ReynosoFrancisco/FranciscoJRO.txt
Listo profe, ya quedó la práctica 1
=> [Add] nombre de usuario a la p1

practicas/1/QuintanaLuis/LuisQuintana23.txt
=> Práctica 1 LuisQuintana23

practicas/1/ArredondoGranados/Gerardo.txt
Agregué mi .txt en mi carpeta correspondiente :)
=> Agrego el nombre de Gerardo Arredondo

practicas/1/LopezAlam/Alam.txt
Agrego el nombre de Alam Lopez
=> Practica 1 -- Alam Lopez Reyes

practicas/1/JimenezAxel/LeXuZz21.txt
Añado el archivo de texto solicitado para la primera practica de Sistemas Operativos del semestre 2024-2
=> Agrego el nombre de Jimenez Axel 

practicas/1/QuintanaErnesto/ernesto.txt
Nombre de [Ernesto Quintana] Agregado
=> Agrego el nombre de Ernesto Quintana Practica 1

practicas/1/GonzalezDavid/david.txt
Agregando el archivo .txt creado para la realización de la práctica 1.
=> 'Agrego el nombre de David Gonzalez'

practicas/1/BarriosMichelle/milliyx.txt
=> [mod] 01022024 P1: Agrego el nombre de Michelle Barrios

practicas/1/PinedaRicardo/PinedaRicardo.txt
Cree la carpeta dentro de practicas/1 con el formato establecido y cree el archivo de texto indicando mi nombre completo y el nombre de usuario que tengo en github
=> Agrego el nombre de Pineda Galindo Ricardo Angel

practicas/1/ZenonPlataAndreaSofia/andyxe.txt
Creacion de un archivo txt con mi nombre real y mi nombre de usuario
=> Agrego el nombre de Andrea Sofia Zenon Plata

practicas/1/PachecoPachecoAdrianAlejandro/Adrian-pacheco08.txt
Realice los cambios señalados y agregue mi nombre de usuario y mi nombre real.
=> Agrego el nombre de Adrian Alejandro Pacheco Pacheco

practicas/1/HernandezMiguel/Miguel-Angel-Hernandez-Ramirez07.txt, practicas/1/RamirezMiguel/Miguel-Angel-Hernandez-Ramirez07.txt
Realize los cambios necesarios para la practica 1, agregando un mensaje en un documento txt
=> Agrego el nombre de Miguel Angel Hernandez Ramirez

practicas/1/AlejandroVigi/Alejandro-Vigi.txt
Se realizó la entrega de la practica 1.
=> Agrego el nombre de Marco Alejandro Vigi Garduño

practicas/1/DominguezJesus/iDuffz.txt
Configuré mi git y cree esta .txt con mi nombre de usuario y mi nombre completo. Ahora estoy haciendo un pull request para entregar mi practica 1.
=> Agrego el nombre de Jesus Abner Dominguez Chavez

practicas/1/SanchezSaida/SaidaSanchez30.txt
Realice los cambios que la práctica menciona. También agregue mi nombre de usuario y mi nombre real en un archivo txt dentro del repositorio
=> Agrego el nombre Saida Mayela Sanchez Calvillo

practicas/1/ChongSamuel/ChongSamuel.txt
Se realizó la práctica 1, creando un txt donde menciono mi nombre y nombre de usuario, se hace un pull request en Git.
=> Agrego el nombre de Samuel Chong Hernandez

practicas/1/RosasIsaias/RedoMarshallX.txt
Cree el archivo RedoMarshallX.txt para indicar mi verdadero nombre y así cumplir con la práctica 1.
=> Agrego el nombre de Isaias Rosas Meza

practicas/1/MirandaFrancisco/FranciscoMiranda13.txt, practicas/1/MirandaFrancisco/francisco.txt
nombre de usuario y nombre real
=> Practica 1

practicas/1/HernandezGutierrez/HernandezGutierrez.txt
Se creo una carpeta con mi nombre para la practica 1 y se hizo un archivo de texto.
=> Agrego el nombre de HernandezGutierrez

practicas/1/LeonErick/ErickLeonG.txt
Entrego mi primer practica. Gracias profesor :)
=> Agrego mi nombre: Erick Leon

practicas/1/FigueroaCarlos/RankFoil.txt
Entrega de práctica 1 de Carlos Figueroa
=> Agrego el nombre de Carlos Figueroa

practicas/1/GalindoFrancisco/Francisco-Galindo.txt
Esta pull-request es correspondiente a la práctica 1.
=> Agrego el nombre de Francisco Galindo

practicas/1/PozosAngel/AngelPozoos.txt
=> Agrego el nombre de Angel Pozos

practicas/1/CruzArmando/ArmandoCM1.txt
Se creo una carpeta con el nombre CruzArmando y tiene un archivo .txt donde indica mi nombre completo
=> Este es la practica 1

practicas/1/LopezFrancisco/francisco.txt
Agrego el nombre Francisco Lopez para completar la entrega de la práctica 1.
=> Práctica 1 - Francisco López

practicas/1/DeLaMercedSorianoUriel/uriel.txt
=> De La Merced Soriano Uriel, pract 1

practicas/1/MartinezIsrael/israel.txt
Se creo el archivo israel.txt que contiene mi nombre y username
=> Agrego el nombre de Israel Martinez

practicas/1/FloresEvelyn/evlee11.txt, practicas/1/evlee11.txt
Intenté desde la terminal desde mi computadora pero no me dejó, marcaba error puesto que tenia otra cuenta anteriormente, sin embargo a esa cuenta ya no tengo acceso, asi que el procesos lo he hecho desede la interfaz grafica.
=> Agrego el nombre Evelyn Flores

practicas/2/ReynosoFrancisco/A/hora_actual.txt, practicas/2/ReynosoFrancisco/hora_actual.txt
=> Practica2a

practicas/2/AguilarErick/heartbleed.txt
Se creo el archivo <code>practicas\2\AguilarErick\heartbleed.txt</code>
=> Agrego el archivo de Erick Aguilar para la práctica 2B

practicas/2/LopezFrancisco/B/cpuinfo.txt
Agrego los datos sobre mi equipo contenidos en el archivo cpuinfo.txt.
=> Agrego el archivo de Francisco Lopez para la práctica 2B

practicas/2/ReyesLuis/A/hora_actual.txt
Se crea la rama practica2a y se agrega el archivo hora_actual.txt
=> Agrego el archivo de Luis Fernando Reyes Romero para la práctica 2A

practicas/2/ReyesLuis/B/cpuinfo.txt
Se crea la rama practica2b y se agrega el archivo cpuinfo.txt
=> Agrego el archivo de Luis Fernando Reyes Romero para la práctica 2B

practicas/2/MirandaFrancisco/B/cpuinfo.txt
=> Agrego el archivo de Francisco Miranda para la práctica 2B

practicas/1/RicoAdrian/CapitanPAN.txt
Buena tarde profesor, disculpe la demora en la entrega de esta práctica pero soy de altas y bajas, así que nos dios hasta el día martes para entregarla. Soy Adrián Rico Posadas.
1. Cree mi cuenta de usuario agregando los dos correos que tengo del dominio UNAM, esperando que pudiera obtener una versión "mejor" de Git para la universidad, pero creo que no se pudo.
2. Realicé el fork directamente desde el navegador web, ya que supongo que es la forma más sencilla de hacerlo.
3. Descargué Git desde la página principal para Windows.
4. Ya en la terminal, cloné el repositorio, aun que solo me funcionó con la segunda opción, considero que por le sistema operativo.
5. Para lograr entrar mas a profundidad en el directorio de la asignatura decidí entrar con "cd " hasta practicas/1/ y ya de ahí cree …
=> Agrego el nombre de Adrian Rico Posadas

practicas/2/FigueroaCarlos/B/cpuinfo.txt
Agrego el archivo de Gunnar Wolf para la práctica 2B
=> Practica2b

practicas/2/CruzArmando/B/cpuinfo.txt
esta es la modificacion de la practica 2 para la seccion B
=> Agrego el archivo de Armando Cruz para la práctica 2B

tareas/1/ZenonAndrea_BarriosMichelle/sistop_t1.py
Entrega en equipo
Barrios Aguilar Dulce Michelle
Zenón Plata Andrea Sofía
=> Agrego tarea 1

tareas/1/ChongSamuel/Tareas_sistop.java
=> Tarea1 ChongHernandezSamuel

tareas/1/DominguezJesus/T1_DominguezJesus.java
Se hace entrega de la tarea 1 en codigo java correspondiente a la asignación de memoria mediante el método de primer ajuste.
=> Agrego el archivo de Dominguez Jesus para la Tarea 1

tareas/1/LopezFrancisco/tarea1.c
Agrego el programa en lenguaje C correspondiente a la tarea 1.
=> Entrega de tarea 1.

tareas/1/MirandaFrancisco/T1.py
Archivo T1.py para la Tarea 1.
=> Agrego el archivo de Francisco Miranda para la tarea 1

practicas/4/ReyesLuis/.gitignore, practicas/4/ReyesLuis/hola.c
Se agregan los archivos de la práctica 4, los cuales son el programa hola mundo en el lenguaje de programación en C. Además del archivo .gitignore para que se ignore el archivo con extensión .exe.
=> Archivos de la practica 4

practicas/4/GonzalezDavid/.gitignore, practicas/4/GonzalezDavid/holamundoD.py
Agregando archivos empleados en la practica 4, tanto el .gitignore como el archivo que generará un .txt que será el elemento a ignorar.
=> Practica 4

practicas/4/BarriosMichelle/.gitignore, practicas/4/BarriosMichelle/rendimiento_arreglo.c
añadí al directorio .gitignore a ./vscode ya que contiene configuraciones específicas para Visual Studio Code.
=> Practica 4 Barrios Michelle

practicas/4/DominguezJesus/.gitignore, practicas/4/DominguezJesus/practica4.c
Se hace entrega de la practica 4
=> Entrego Practica 4 - Dominguez Chavez Jesus Abner

practicas/4/GalindoFrancisco/.gitignore, practicas/4/GalindoFrancisco/memoria.sh
Esta Pull Request tiene lo correspondiente a la práctica 4
=> Práctica 4 Francisco Galindo

practicas/4/CruzArmando/.gitignore, practicas/4/CruzArmando/hola.c
anexo los archivos de la practica 4
=> Entrega de la practica 4

proyectos/1/DominguezJesus-SanchezSaida/proyecto.py
Se agrega las bases del codigo incluyendo la lectura del superbloque y el menu
=> Proyecto 1 Dominguez Jesus y Sanchez Saida
